version: "3.7"
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      target: release 
      args:
        PYTHON_VERSION: 3.7.3
    image: game-backend:release-3.7.3
    ports: 
      - '5000:5000'
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      target: release 
      args: 
        NODE_VERSION: 10
    image: game-frontend:release-10
    ports: 
      - '3000:3000'
